Fixed npm install error
The current version on npm does not install correctly. It fails on the
browserify command:

browserify -d -o node-xmpp-browser.js lib/node-xmpp-browserify.js

The error browserify gives is:

Error: Cannot find module: "JID" from directory

This is caused by an incorrect require in lib/node-xmpp-browserify.js
which I fixed in this commit.